Fix command line tool for colornet
The following error was raised when running the tool in cpu mode:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

This should be changed in future to set the map_location depending if cuda is available or not